FROM maven:3.8.4-openjdk-17 as build
WORKDIR /app
COPY . /app
RUN mvn clean install

FROM openjdk:17-alpine
COPY --from=build /app/target/fleet-core-backend-0.0.1-SNAPSHOT.jar /fleet-core-backend.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/fleet-core-backend.jar"]