import { environment } from "src/environments/environment";

// API URL
export const API_URL = environment.API_URL;

// WEBSOCKET FOR LIVE DRIVER UPDATES
export const SOCKET_LIVE_LOCATION_URL = environment.SOCKET_LIVE_LOCATION_URL;
export const SOCKET_LIVE_LOCATION_UPDATE_URL = environment.SOCKET_LIVE_LOCATION_UPDATE_URL;
export const SOCKET_LIVE_LOCATION_SUSBSCRIBE_URL = environment.SOCKET_LIVE_LOCATION_SUBSCRIBE_URL;

export const SOCKET_ALERTS_UPDATE_URL = environment.SOCKET_ALERTS_UPDATE_URL;
export const SOCKET_ALERTS_SUBSCRIBE_URL = environment.SOCKET_ALERTS_SUBSCRIBE_URL;

export const SOCKET_ROUTE_STATUS_UPDATE_URL = environment.SOCKET_ROUTE_STATUS_UPDATE_URL;
export const SOCKET_ROUTE_STATUS_SUBSCRIBE_URL = environment.SOCKET_ROUTE_STATUS_SUBSCRIBE_URL;

export const TOKEN_ENCRYPTION_SECRET = environment.TOKEN_ENCRYPTION_SECRET;

export const GOOGLE_MAPS_API_KEY = environment.GOOGLE_MAPS_API_KEY;
