# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fleet-core-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/email-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1f65c897a0c54c84958ccc3e46c35b8f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b78b1b58b510406b8f77d59afd21aa67 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1f65c897a0c54c84958ccc3e46c35b8f }}/fleet-core-backend:${{ github.sha }}
        file: ./Dockerfile-Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fleet-core-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22336e08989745ff83972d14d2aa3f6d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1f65c897a0c54c84958ccc3e46c35b8f }}/fleet-core-backend:${{ github.sha }}'
