# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fleet-core-frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/email-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_64e618ff5107472c8f12be39490fee86 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9a1a305644a497ebc8d36e85b6d638e }}


    - name: Build and push container image to registry
      run: |
        cd src/main/resources/fleet-core-frontend
        docker build -t index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64e618ff5107472c8f12be39490fee86 }}/fleet-core-frontend:${{ github.sha }} -f Dockerfile-Frontend .
        docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64e618ff5107472c8f12be39490fee86 }}/fleet-core-frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fleet-core-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10bb88ad5b4c46dd93a017e5e4fe6b4e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64e618ff5107472c8f12be39490fee86 }}/fleet-core-frontend:${{ github.sha }}'
